### PR TITLE
remove appliedTo security group from rule description

### PR DESCRIPTION
**Pull request by shenmo3**
## Description
The rule description field on AWS has a char limit of 255 and on Azure 140. To conserve space and allowing longer possible ANP names, we want to remove appliedTo security group field from cloud rule descriptions, as these information can be directly inferred from rule properties.

## Changes
1. Remove at sg from cloud rule description and update corresponding helper functions.
2. Change Azure rule logic to use sgs in rule properties instead of parsing from description (AWS is already using rule properties).

### CODE REVIEW

**Review by reachjainrahul — DISMISSED** [review]
/LGTM

**Comment by reachjainrahul** [comment]
/nephe-test-e2e-kind, /nephe-test-e2e-eks, /nephe-test-e2e-aks

**Comment by reachjainrahul** [comment]
/nephe-test-e2e-kind, /nephe-test-e2e-eks, /nephe-test-e2e-aks

**Comment by shenmo3** [comment]
/nephe-test-e2e-kind, /nephe-test-e2e-eks, /nephe-test-e2e-aks

**Review by reachjainrahul — APPROVED** [review]
/LGTM

**Pull request merged**
